### ISSUE TITLE
Retire puppet-imagemagick?

### ISSUE THREAD

**Issue by seanknox** [boxen/puppet-imagemagick#13]
I don't see what this module provides that is special over a standard homebrew installation. @boxen/owners do you know?

**Comment by rafaelfranca** [comment]
Yes. It ensure that everyones use the same version of imagemagick. Almost all the modules that are just wrappers around homebrew formulas are just to ensure this since homebrew don't have a way to install an specific version and freeze it.

So freezing homebrew formulas like this module is doing is the only way to ensure that everyone in your organization will use a version that is tested and works for your organization.

**Comment by seanknox** [comment]
Might we better off with allowing users to specify a version of a Homebrew
formula, rather than this need for custom boxen modules for that simple
feature?

**Comment by rafaelfranca** [comment]
yeah. that would be really good, but it is not possible right now with homebrew :cry:

**Comment by mikemcquaid** [comment]
Most Boxen modules don't provide anything over the Homebrew installation, just usnig the same version (as @rafaelfranca mentions).

FWIW I think this is mostly a waste of time and the better fit is using/submitting to e.g. `homebrew-versions` for applications where this actually matters. MySQL is an application where I can see the use-case, ImageMagick is not, personally. That said: probably not worth "retiring" any of these modules as people are still using them.

**Comment by seanknox** [comment]
Thanks @mikemcquaid, makes loads of sense.
